# Task1 作业

难

## 1. 导入 numpy 库并简写为 np

In [1]:
import numpy as np

## 2. 打印 numpy 的版本和配置说明

In [2]:
import numpy as np
np.__version__

'1.16.2'

In [5]:
import numpy as np
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chenguoyi/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/chenguoyi/AppData/Local/Continuum/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chenguoyi/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program File

## 3. 创建一个长度为10的空向量

In [7]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. 如何找到任何一个数组的内存大小？

In [10]:
import numpy as np
a = np.ones(20)
print(f'{a.size * a.itemsize}')

160


## 5. 如何从命令行得到 numpy 中 add 函数的说明文档?

In [12]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 6. 创建一个长度为 10 并且除了第五个值为 1 的空向量

In [14]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. 创建一个值域范围从10到49的向量

In [17]:
import numpy as np
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 8. 反转一个向量(第一个元素变为最后一个) 

In [19]:
import numpy as np
nd = np.arange(10, 50)
nd[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 9. 创建一个 3x3 并且值从 0 到 8 的矩阵

In [25]:
import numpy as np
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10. 找到数组 [1,2,0,0,4,0] 中非0元素的位置索引

In [27]:
import numpy as np
a = np.nonzero([1, 2, 0, 0, 4, 0])
print(a)

(array([0, 1, 4], dtype=int64),)


## 11. 创建一个 3x3 的单位矩阵

In [30]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 12. 创建一个 3x3x3 的随机数组

In [34]:
import numpy as np
np.random.random((3, 3, 3))

array([[[0.37145454, 0.54907161, 0.3127398 ],
        [0.61758176, 0.17047275, 0.79280429],
        [0.13157214, 0.087634  , 0.70286895]],

       [[0.77126543, 0.43566322, 0.90610934],
        [0.48500934, 0.42279778, 0.67368269],
        [0.57313692, 0.30507815, 0.69880286]],

       [[0.64217586, 0.39816547, 0.29517148],
        [0.5900942 , 0.19869637, 0.53326499],
        [0.5738129 , 0.75625497, 0.29137537]]])

## 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [36]:
import numpy as np
nr = np.random.random((10, 10))
print(nr.max())
print(nr.min())

0.9976993260760499
0.012049719803920111


## 14. 创建一个长度为 30 的随机向量并找到它的平均值

In [39]:
import numpy as np
a = np.random.random(30)
b = a.mean()
print(b)

0.4798068251144129


## 15. 创建一个二维数组，其中边界值为 1，其余值为 0

In [41]:
import numpy as np
c = np.ones((5, 5))
c[1:-1, 1:-1] = 0
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 16. 对于一个存在在数组，如何添加一个用 0 填充的边界? 

numpy.pad(array, pad_width, mode, **kwargs)

**参数解释：**  

    array——表示需要填充的数组；

    pad_width——表示每个轴（axis）边缘需要填充的数值数目。
    参数输入方式为：（(before_1, after_1), … (before_N, after_N)），其中(before_1, after_1)表示第1轴两边缘分别填充before_1个和after_1个数值。取值为：{sequence, array_like, int}

    mode——表示填充的方式（取值：str字符串或用户提供的函数）,总共有11种填充模式；


**填充方式：**  


    ‘constant’——表示连续填充相同的值，每个轴可以分别指定填充值，constant_values=（x, y）时前面用x填充，后面用y填充，缺省值填充0

    ‘edge’——表示用边缘值填充

    ‘linear_ramp’——表示用边缘递减的方式填充

    ‘maximum’——表示最大值填充

    ‘mean’——表示均值填充

    ‘median’——表示中位数填充

    ‘minimum’——表示最小值填充

    ‘reflect’——表示对称填充

    ‘symmetric’——表示对称填充

    ‘wrap’——表示用原数组后面的值填充前面，前面的值填充后面


In [82]:
import numpy as np
nd = np.arange(1, 10)
df = np.pad(nd, (1, 1), 'constant')
df

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [1]:
import numpy as np
array = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                 [[10, 11, 12], [13, 14, 15,], [49, 32, 21]],
                 [[16, 12, 11,], [19, 0, 8], [23, 21, 34]]])
data = np.pad(array, pad_width=1, mode='constant', constant_values=0)
data

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  0],
        [ 0,  4,  5,  6,  0],
        [ 0,  7,  8,  9,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0, 10, 11, 12,  0],
        [ 0, 13, 14, 15,  0],
        [ 0, 49, 32, 21,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0, 16, 12, 11,  0],
        [ 0, 19,  0,  8,  0],
        [ 0, 23, 21, 34,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]]])

## 17. 以下表达式运行的结果分别是什么?

0 * np.nan  
np.nan == np.nan  
np.inf > np.nan  
np.nan - np.nan  
0.3 == 3 * 0.1

In [2]:
import numpy as np

In [3]:
print(0 * np.nan)

nan


In [4]:
print(np.nan == np.nan)

False


In [5]:
print(np.inf > np.nan)

False


In [6]:
print(np.nan - np.nan)

nan


In [7]:
print(0.3 == 3 * 0.1)

False


## 18. 创建一个 5x5 的矩阵，并设置值 1,2,3,4 落在其对角线下方位置

**numpy.diag(v,k=0)**  
diag 函数功能：矩阵对角元素的提取和创建对角阵

参数详解：

    v : array_like.

如果 v 是 2D 数组，返回 k 位置的对角线。

如果 v 是 1D 数组，返回一个 v 作为 k 位置对角线的 2D 数组。

    k : int, optional

默认值为 0，对角线的位置，大于零位于对角线上面，小于零则在下面。

In [11]:
array = np.diag(1 + np.arange(4), k=-1)
array

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [16]:
Z = np.zeros((8, 8), dtype=int)
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [12]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 20. 考虑一个 (6,7,8) 形状的数组，其第 100 个元素的索引 (x,y,z) 是什么?

 **numpy.unravel_index(indices, shape, order='C')**

    将平面索引或平面索引数组转换为坐标数组的元组。  
    函数的作用是获取一个/组int类型的索引值在一个多维数组中的位置

参数:	

indices 指数 : array_like

    一个整数数组，其元素是维度数组的扁平版本的索引。 shape . 在版本1.6.0之前，此函数只接受一个索引值。
    
    参数 indices 除了可以是 int 型标量值，还可以是一个 int 型数组，当 indices 为 int 型数组时，就是对数组中的每一个元素执行相同的运算过程.
    
shape 形状 : 整数元组

    用于分解的数组的形状 indices .

    在 1.16.0 版更改: 更名为 dims 到 shape .
order 秩序 : 'C'、'F'，可选

    确定索引应按行主索引（C样式）还是列主索引（Fortran样式）顺序查看。

    1.6.0 新版功能.



返回:	

unraveled_coords : Ndarray的元组

    元组中的每个数组的形状与 indices 数组。


In [26]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [21]:
np.unravel_index([22, 41, 37], (7, 6))

(array([3, 6, 6], dtype=int64), array([4, 5, 1], dtype=int64))

In [23]:
np.unravel_index([22, 41, 37], (7, 6), order='F')

(array([1, 6, 2], dtype=int64), array([3, 5, 5], dtype=int64))

***numpy.ravel_multi_index() 执行和 np.unravel_index() 函数相反的运算***

In [25]:
np.ravel_multi_index((1, 5, 4), (6, 7, 8))

100

 **numpy.ravel_multi_index(multi_index, dims, mode='raise', order='C')**

    将索引数组的元组转换为平面索引数组，并将边界模式应用于多索引。

参数:	

multi_index : 数组元组

    整数数组的元组，每个维度一个数组。
dims : 整数元组

    索引所在的数组的形状 multi_index 申请。
mode : 'raise'、'wrap'、'clip'，可选

    指定如何处理越界索引。可以指定一个模式或模式的元组，每个索引一个模式。

        “raise”--引发错误（默认）
        “环绕”—环绕
        '剪辑'--剪辑到范围

    在“剪辑”模式下，通常会自动换行的负索引将剪辑为0。
秩序 : 'C'、'F'，可选

    确定多索引应按行主索引（C样式）还是列主索引（Fortran样式）顺序查看。

返回:	

raveled_indices : 恩达雷

    维度数组的扁平版本中的索引数组。 dims .


主要功能为把给定的一个多维数组（函数的第一个参数 multi_index）看作索引数组，索引什么呢？去索引一个形状为 dims（函数的第二个参数），值为依次增大的自然数的数组中的值（可看做由list(range(N)) 的数组 reshape(dims) 而来），意义即为用一个唯一的一维数来定位（保存）原数组的二维（或多维(i,j,k,…)）的数对的信息。

In [24]:
arr = np.array([[3, 6, 6], [4, 5, 1]])
np.ravel_multi_index(arr, (7, 6))

array([22, 41, 37], dtype=int64)

示例中 arr 即为要转换的多维数组，把 arr 的内容当作索引，即 [3,6,6] 为横坐标，[4,5,1] 为纵坐标，去索引形状为(7,6)，内容为从 0 开始，从左往右，从上往下依次增大的自然数的数组中的值。

例如第一个要索引的数 [3,4] 即为 (7,6) 数组中第4行，第5列的的值，即为 3*6+4=22，即为结果中的第一个数。依次类推。

## 21. 用 tile 函数去创建一个 8x8 的棋盘样式矩阵

 numpy.tile(A, reps)[源代码]

    通过重复reps给出的次数构造数组。

    如果 reps 有长度 d ，结果的维数为 max(d, A.ndim) .

    如果 A.ndim < d ， A 通过预处理新轴提升为三维。因此，对于二维复制，形状（3，3）数组提升为（1，3），对于三维复制，形状（1，1，3）。如果这不是所需的行为，请提升 A 在调用此函数之前手动转换为D维。

    如果 A.ndim > d ， reps 被提升为 A .ndim通过预挂起1对它。因此，对于 A 形状（2，3，4，5），a reps （2，2）被视为（1，1，2，2）。

    注：虽然瓷砖可用于广播，但强烈建议使用Numpy的广播操作和功能。

参数:	

A : array_like

    输入数组。
reps : array_like

    重复次数 A 沿着每个轴。

返回:	

c : 恩达雷

    平铺的输出数组。


In [31]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 22. 对一个 5x5 的随机矩阵做归一化

In [34]:
Z = np.random.random((5, 5))
# print(Z)
Zmax, Zmin = Z.max(), Z.min()
a = (Z-Zmin) / (Zmax-Zmin)
print(a)

[[0.7008991  0.45551221 0.33965984 0.19950597 0.32753296]
 [0.14622621 0.14545997 0.11085606 1.         0.89025136]
 [0.         0.29610483 0.30507795 0.71931492 0.83870748]
 [0.71449552 0.56913647 0.50000531 0.50499405 0.0448187 ]
 [0.90870263 0.44597039 0.8732081  0.15513325 0.98025052]]


[归一化 （Normalization）、标准化 （Standardization）和中心化/零均值化 （Zero-centered）](https://www.jianshu.com/p/95a8f035c86c)

[归一化和标准化大全](https://www.jianshu.com/p/c1e112f3f57f)

## 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [35]:
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                 ("b", np.ubyte, 1),
                 ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

## 24. 一个 5x3 的矩阵与一个 3x2 的矩阵相乘，实矩阵乘积是什么？

In [39]:
a = np.arange(15).reshape(5, 3)
b = np.arange(6).reshape(3, 2)
d = np.dot(a, b)
print(d)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


## 25. 给定一个一维数组，对其在 3 到 8 之间的所有元素取反

In [42]:
Z = np.arange(20)
print(Z)
print("--------------------------------------------")
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
--------------------------------------------
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


## 26. 下面脚本运行后的结果是什么?

In [43]:
print(sum(range(5), -1))

9


In [44]:
from numpy import *
print(sum(range(5), -1))

10


## 27. 考虑一个整数向量 Z,下列表达合法的是哪个?

Z**Z  
2 << Z >> 2  
Z <- Z  
1j*Z  
Z/1/1  
Z<Z>Z  

## 28. 下列表达式的结果分别是什么?

np.array(0) / np.array(0)  
np.array(0) // np.array(0)  
np.array([np.nan]).astype(int).astype(float)  

## 29. 如何从零位对浮点数组做舍入 ?

## 30. 如何找到两个数组中的共同元素? 

## 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?

## 32. 下面的表达式是正确的吗?

## 33. 如何得到昨天，今天，明天的日期?

## 34. 如何得到所有与2016年7月对应的日期？

## 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

## 36. 用五种不同的方法去提取一个随机数组的整数部分

## 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

## 38. 通过考虑一个可生成10个整数的函数，来构建一个数组

## 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

## 40. 创建一个长度为10的随机向量，并将其排序

## 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？

## 42. 对于两个随机数组A和B，检查它们是否相等

## 43. 创建一个只读数组(read-only)

## 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

## 45. 创建一个长度为10的向量，并将向量中最大值替换为1 

## 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

## 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

## 48. 打印每个numpy标量类型的最小值和最大值？

## 49. 如何打印一个数组中的所有数值? 

## 50. 给定标量时，如何找到数组中最接近标量的值？

## 51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组

## 52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离

## 53. 如何将32位的浮点数(float)转换为对应的整数(integer)?

## 54. 如何读取以下文件?

## 55. 对于numpy数组，enumerate的等价操作是什么？

## 56. 生成一个通用的二维Gaussian-like数组

## 56. 生成一个通用的二维Gaussian-like数组

## 57. 对一个二维数组，如何在其内部随机放置p个元素?

## 58. 减去一个矩阵中的每一行的平均值

## 59. 如何通过第n列对一个数组进行排序?

## 60. 如何检查一个二维数组是否有空列？

## 61. 从数组中的给定值中找出最近的值

## 62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?

## 63. 创建一个具有name属性的数组类

## 64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)?

## 65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)?

## 66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量(★★★)

## 67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？

## 68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

## 69. 如何获得点积 dot prodcut的对角线?

## 70. 考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？

## 71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？

## 72. 如何对一个数组中任意两行做交换? 

## 73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

## 74. 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C

## 75. 如何通过滑动窗口计算一个数组的平均数?

## 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

## 77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？

## 78. 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？

## 79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？

## 80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

## 81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? 

## 82. 计算一个矩阵的秩

## 83. 如何找到一个数组中出现频率最高的值？

## 84. 从一个10x10的矩阵中提取出连续的3x3区块

## 85. 创建一个满足 Z[i,j] == Z[j,i]的子类

## 86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？

## 87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)?

## 88. 如何利用numpy数组实现Game of Life?

## 89. 如何找到一个数组的第n个最大值?

## 90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)

## 91. 如何从一个正常数组创建记录数组(record array)?

## 92. 考虑一个大向量Z, 用三种不同的方法计算它的立方

## 93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？

## 94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3])

## 95. 将一个整数向量转换为matrix binary的表现形式

## 96. 给定一个二维数组，如何提取出唯一的(unique)行?

## 97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数

## 98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)? 

## 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. 

## 100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。