# Task1 作业

1. 导入 numpy 库并简写为 np

In [1]:
import numpy as np

2. 打印 numpy 的版本和配置说明

In [2]:
import numpy as np
np.__version__

'1.16.2'

In [5]:
import numpy as np
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chenguoyi/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/chenguoyi/AppData/Local/Continuum/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/chenguoyi/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program File

3. 创建一个长度为10的空向量

In [7]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. 如何找到任何一个数组的内存大小？

In [10]:
import numpy as np
a = np.ones(20)
print(f'{a.size * a.itemsize}')

160


5. 如何从命令行得到 numpy 中 add 函数的说明文档?

In [12]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6. 创建一个长度为 10 并且除了第五个值为 1 的空向量

In [14]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量

In [17]:
import numpy as np
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. 反转一个向量(第一个元素变为最后一个) 

In [19]:
import numpy as np
nd = np.arange(10, 50)
nd[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. 创建一个 3x3 并且值从 0 到 8 的矩阵

In [25]:
import numpy as np
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组 [1,2,0,0,4,0] 中非0元素的位置索引

In [27]:
import numpy as np
a = np.nonzero([1, 2, 0, 0, 4, 0])
print(a)

(array([0, 1, 4], dtype=int64),)


11. 创建一个 3x3 的单位矩阵

In [30]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. 创建一个 3x3x3 的随机数组

In [34]:
import numpy as np
np.random.random((3, 3, 3))

array([[[0.37145454, 0.54907161, 0.3127398 ],
        [0.61758176, 0.17047275, 0.79280429],
        [0.13157214, 0.087634  , 0.70286895]],

       [[0.77126543, 0.43566322, 0.90610934],
        [0.48500934, 0.42279778, 0.67368269],
        [0.57313692, 0.30507815, 0.69880286]],

       [[0.64217586, 0.39816547, 0.29517148],
        [0.5900942 , 0.19869637, 0.53326499],
        [0.5738129 , 0.75625497, 0.29137537]]])

13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [36]:
import numpy as np
nr = np.random.random((10, 10))
print(nr.max())
print(nr.min())

0.9976993260760499
0.012049719803920111


14. 创建一个长度为 30 的随机向量并找到它的平均值

In [39]:
import numpy as np
a = np.random.random(30)
b = a.mean()
print(b)

0.4798068251144129


15. 创建一个二维数组，其中边界值为 1，其余值为 0

In [41]:
import numpy as np
c = np.ones((5, 5))
c[1:-1, 1:-1] = 0
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. 对于一个存在在数组，如何添加一个用 0 填充的边界? 

numpy.pad(array, pad_width, mode, **kwargs)

**参数解释：**  

    array——表示需要填充的数组；

    pad_width——表示每个轴（axis）边缘需要填充的数值数目。
    参数输入方式为：（(before_1, after_1), … (before_N, after_N)），其中(before_1, after_1)表示第1轴两边缘分别填充before_1个和after_1个数值。取值为：{sequence, array_like, int}

    mode——表示填充的方式（取值：str字符串或用户提供的函数）,总共有11种填充模式；


**填充方式：**  


    ‘constant’——表示连续填充相同的值，每个轴可以分别指定填充值，constant_values=（x, y）时前面用x填充，后面用y填充，缺省值填充0

    ‘edge’——表示用边缘值填充

    ‘linear_ramp’——表示用边缘递减的方式填充

    ‘maximum’——表示最大值填充

    ‘mean’——表示均值填充

    ‘median’——表示中位数填充

    ‘minimum’——表示最小值填充

    ‘reflect’——表示对称填充

    ‘symmetric’——表示对称填充

    ‘wrap’——表示用原数组后面的值填充前面，前面的值填充后面


In [82]:
import numpy as np
nd = np.arange(1, 10)
df = np.pad(nd, (1, 1), 'constant')
df

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [80]:
import numpy as np
array = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                 [[10, 11, 12], [13, 14, 15,], [49, 32, 21]],
                 [[16, 12, 11,], [19, 0, 8], [23, 21, 34]]])
data = np.pad(array, pad_width=1, mode='constant', constant_values=0)
data

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  0],
        [ 0,  4,  5,  6,  0],
        [ 0,  7,  8,  9,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0, 10, 11, 12,  0],
        [ 0, 13, 14, 15,  0],
        [ 0, 49, 32, 21,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0, 16, 12, 11,  0],
        [ 0, 19,  0,  8,  0],
        [ 0, 23, 21, 34,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]]])